import { createSlice } from "@reduxjs/toolkit";
import { HYDRATE } from "next-redux-wrapper";

const initialState = {
  items: [
    {
      id: "cat-1",
      category: "ONE SOUND CRACKERS",
      description: "description",
      items: [
        {
          id: "1",
          name: "2 3/4 Kuruvi",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 9,
          qty: "",
          total: "",
        },
        {
          id: "2",
          name: "3 1/2 Lakshmi ",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 15,
          qty: "",
          total: "",
        },
        {
          id: "3",
          name: "4'Lakshmi",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 15,
          qty: "",
          total: "",
        },
        {
          id: "4",
          name: "4' Gold Lakshmi",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 20,
          qty: "",
          total: "",
        },
        {
          id: "5",
          name: "4' Joker",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 30,
          qty: "",
          total: "",
        },
        {
          id: "6",
          name: "4' Hulk",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 30,
          qty: "",
          total: "",
        },
        {
          id: "7",
          name: "5' Lakshmi",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 50,
          qty: "",
          total: "",
        },
        {
          id: "8",
          name: "6' Lakshmi",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 55,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-2",
      category: "PAPER SOUND CRACKERS",
      description: "description",
      items: [
        {
          id: "9",
          name: "4' Kattu Vedi",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 20,
          qty: "",
          total: "",
        },
        {
          id: "10",
          name: "5' Kattu Vedi",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 40,
          qty: "",
          total: "",
        },
        {
          id: "11",
          name: "6' Kattu Vedi",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 60,
          qty: "",
          total: "",
        },
        {
          id: "12",
          name: "10'1/2 Gold",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 80,
          qty: "",
          total: "",
        },
        {
          id: "13",
          name: "1/4 Paper Bom",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 50,
          qty: "",
          total: "",
        },
        {
          id: "14",
          name: "1/2 Paper Bom",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 125,
          qty: "",
          total: "",
        },
        {
          id: "15",
          name: "3/4 Paper Bom",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 180,
          qty: "",
          total: "",
        },
        {
          id: "16",
          name: "Avathar - 1 - 10 pcs",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 300,
          qty: "",
          total: "",
        },
        {
          id: "17",
          name: "Avathar - 2 - 10 pcs",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 400,
          qty: "",
          total: "",
        },
        {
          id: "18",
          name: "Chinna Mapala",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 300,
          qty: "",
          total: "",
        },
        {
          id: "19",
          name: "Periya Mapala",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 600,
          qty: "",
          total: "",
        },
        {
          id: "20",
          name: "Olai Vedi",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 90,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-3",
      category: "ELECTRIC CRACKERS",
      description: "description",
      items: [
        {
          id: "21",
          name: "100 W/K",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 40,
          qty: "",
          total: "",
        },
        {
          id: "22",
          name: "200 W/K",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 80,
          qty: "",
          total: "",
        },
        {
          id: "23",
          name: "300 W/K",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 120,
          qty: "",
          total: "",
        },
        {
          id: "24",
          name: "600 W/K",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 180,
          qty: "",
          total: "",
        },
        {
          id: "25",
          name: "1000 W/K",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 320,
          qty: "",
          total: "",
        },
        {
          id: "26",
          name: "2000 W/K",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 460,
          qty: "",
          total: "",
        },
        {
          id: "27",
          name: "5000 W/K",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 1450,
          qty: "",
          total: "",
        },
        {
          id: "28",
          name: "10000 W/K",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 3850,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-4",
      category: "BIJI CRACKERS",
      description: "description",
      items: [
        {
          id: "29",
          name: "50 Bijili",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 20,
          qty: "",
          total: "",
        },
        {
          id: "30",
          name: "100 Bijili",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 40,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-5",
      category: "CHORASA CRACKERS",
      description: "description",
      items: [
        {
          id: "31",
          name: "28 Chorsa",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 20,
          qty: "",
          total: "",
        },
        {
          id: "32",
          name: "56 Chorsa",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 30,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-6",
      category: "GAINT CRACKERS",
      description: "description",
      items: [
        {
          id: "33",
          name: "28 Gaint",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 20,
          qty: "",
          total: "",
        },
        {
          id: "34",
          name: "56 Gaint",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 30,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-7",
      category: "DELUXE CRACKERS",
      description: "description",
      items: [
        {
          id: "35",
          name: "20 Deluxe",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 20,
          qty: "",
          total: "",
        },
        {
          id: "36",
          name: "24 Deluxe",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 30,
          qty: "",
          total: "",
        },
        {
          id: "37",
          name: "50 Deluxe",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 80,
          qty: "",
          total: "",
        },
        {
          id: "38",
          name: "100 Deluxe",
          img: "img/logo.png",
          unit: "1 PKT",
          actual_amount: "",
          amount: 160,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-8",
      category: "ROCKETS",
      description: "description",
      items: [
        {
          id: "39",
          name: "Rocket Bomb",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 50,
          qty: "",
          total: "",
        },
        {
          id: "40",
          name: "Lunic Express",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 80,
          qty: "",
          total: "",
        },
        {
          id: "41",
          name: "2 Sound Rocket",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 120,
          qty: "",
          total: "",
        },
        {
          id: "42",
          name: "3 Sound Rocket",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 150,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-9",
      category: "GROUND CHAKKAR",
      description: "description",
      items: [
        {
          id: "43",
          name: "Ground Chakkar Big",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 40,
          qty: "",
          total: "",
        },
        {
          id: "44",
          name: "Ground Chakkar Special",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 70,
          qty: "",
          total: "",
        },
        {
          id: "45",
          name: "Ground Chakkar Deluxe",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 150,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-10",
      category: "FLOWER POTS",
      description: "description",
      items: [
        {
          id: "46",
          name: "Flower Pots Big",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 60,
          qty: "",
          total: "",
        },
        {
          id: "47",
          name: "Flower Pots Special",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 100,
          qty: "",
          total: "",
        },
        {
          id: "48",
          name: "Flower Pots Asoka",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 120,
          qty: "",
          total: "",
        },
        {
          id: "49",
          name: "Flower Pots Deluxe",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 170,
          qty: "",
          total: "",
        },
        {
          id: "50",
          name: "Flower Pots AsokaColour Koti ",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 200,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-11",
      category: "BOMS",
      description: "description",
      items: [
        {
          id: "51",
          name: "Atom Bomb",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 50,
          qty: "",
          total: "",
        },
        {
          id: "52",
          name: "Hdyro Bomb",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 100,
          qty: "",
          total: "",
        },
        {
          id: "53",
          name: "King Of King",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 120,
          qty: "",
          total: "",
        },
        {
          id: "54",
          name: "Classi Green",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 170,
          qty: "",
          total: "",
        },
        {
          id: "55",
          name: "Titan",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 200,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-12",
      category: "TWINKLE STAR",
      description: "description",
      items: [
        {
          id: "56",
          name: "1 1/2 Twingling Star",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 30,
          qty: "",
          total: "",
        },
        {
          id: "57",
          name: "4' Twingle Star",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 60,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-13",
      category: "MAX BOX",
      description: "description",
      items: [
        {
          id: "58",
          name: "Small Max Box ( 10 Items)",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 20,
          qty: "",
          total: "",
        },
        {
          id: "59",
          name: "Iddle Max Box ( 10 Box )",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 30,
          qty: "",
          total: "",
        },
        {
          id: "60",
          name: "S.DE Max Box ( 10 Box )",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 80,
          qty: "",
          total: "",
        },
        {
          id: "61",
          name: "Lambal Max Box ( 10 Box )",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 120,
          qty: "",
          total: "",
        },
        {
          id: "62",
          name: "Jumbal ax Box ( 10 Box )",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 150,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-14",
      category: "SPARKERLERS",
      description: "description",
      items: [
        {
          id: "63",
          name: "7 Cm Colours",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 10,
          qty: "",
          total: "",
        },
        {
          id: "64",
          name: "7 Cm Electric",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 10,
          qty: "",
          total: "",
        },
        {
          id: "65",
          name: "10 Cm Colours",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 20,
          qty: "",
          total: "",
        },
        {
          id: "66",
          name: "10 Cm Electric",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 20,
          qty: "",
          total: "",
        },
        {
          id: "67",
          name: "12 Cm Colours",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 25,
          qty: "",
          total: "",
        },
        {
          id: "68",
          name: "12 Cm Electric",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 25,
          qty: "",
          total: "",
        },
        {
          id: "69",
          name: "15 Cm Electric",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 35,
          qty: "",
          total: "",
        },
        {
          id: "70",
          name: "15 Cm Colours",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 40,
          qty: "",
          total: "",
        },
        {
          id: "71",
          name: "30 Cm Electric",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 35,
          qty: "",
          total: "",
        },
        {
          id: "72",
          name: "30 Cm Colours",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 40,
          qty: "",
          total: "",
        },
        {
          id: "73",
          name: "50 Cm Colours",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 200,
          qty: "",
          total: "",
        },
        {
          id: "74",
          name: "50 Cm Electric",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 180,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-15",
      category: "FANCY NOVELTIES",
      description: "description",
      items: [
        {
          id: "75",
          name: "Pamparam - 5 PCS",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 80,
          qty: "",
          total: "",
        },
        {
          id: "76",
          name: "Photo Flash - 5PCS",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 100,
          qty: "",
          total: "",
        },
        {
          id: "77",
          name: "Money Crackers - 2 PCS",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 160,
          qty: "",
          total: "",
        },
        {
          id: "78",
          name: "Drone Crackers - 5 PCS",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 90,
          qty: "",
          total: "",
        },
        {
          id: "79",
          name: "Helicpter - 5 PCS",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 90,
          qty: "",
          total: "",
        },
        {
          id: "80",
          name: "Beer Crackers - 2 PCS",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 140,
          qty: "",
          total: "",
        },
        {
          id: "81",
          name: "Beer Crackers - 1 PCS",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 120,
          qty: "",
          total: "",
        },
        {
          id: "82",
          name: "Sirn - small - 5 PCS",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 80,
          qty: "",
          total: "",
        },
        {
          id: "83",
          name: "Sirn - big - 3 PCS",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 150,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-16",
      category: "COLOUR FOUNTAIN",
      description: "description",
      items: [
        {
          id: "84",
          name: "Jelly - 5 pcs",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 130,
          qty: "",
          total: "",
        },
        {
          id: "85",
          name: "Kukure - 5 pcs",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 180,
          qty: "",
          total: "",
        },
        {
          id: "86",
          name: "Red Roses",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 140,
          qty: "",
          total: "",
        },
        {
          id: "87",
          name: "Green Apple",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 140,
          qty: "",
          total: "",
        },
        {
          id: "88",
          name: " Blue Ice",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 140,
          qty: "",
          total: "",
        },
        {
          id: "89",
          name: "8 Golden Eye",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 140,
          qty: "",
          total: "",
        },
        {
          id: "90",
          name: "Twin tone",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 140,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-17",
      category: "AMAZING FOUNTAIN",
      description: "description",
      items: [
        {
          id: "91",
          name: "Butterscotch",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 120,
          qty: "",
          total: "",
        },
        {
          id: "92",
          name: "Pista",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 120,
          qty: "",
          total: "",
        },
        {
          id: "93",
          name: "Venila",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 120,
          qty: "",
          total: "",
        },
        {
          id: "94",
          name: "Tricolour Fountain",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 220,
          qty: "",
          total: "",
        },
        {
          id: "95",
          name: "Sky King ( 6 Pcs )",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 160,
          qty: "",
          total: "",
        },
        {
          id: "96",
          name: "Peacock - Small",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 180,
          qty: "",
          total: "",
        },
        {
          id: "97",
          name: "Water Falls",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 160,
          qty: "",
          total: "",
        },
        {
          id: "98",
          name: "Popcorn",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 180,
          qty: "",
          total: "",
        },
        {
          id: "99",
          name: "Sivashi Special",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 180,
          qty: "",
          total: "",
        },
        {
          id: "100",
          name: "4 * 4 Wheel",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 180,
          qty: "",
          total: "",
        },
        {
          id: "101",
          name: "Twenty Fountain",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 150,
          qty: "",
          total: "",
        },
        {
          id: "102",
          name: "Water Queen",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 150,
          qty: "",
          total: "",
        },
        {
          id: "103",
          name: "Crackers Queen",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 150,
          qty: "",
          total: "",
        },
        {
          id: "104",
          name: "Old is Gold",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 140,
          qty: "",
          total: "",
        },
        {
          id: "105",
          name: "Sound Marrage",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 50,
          qty: "",
          total: "",
        },
        {
          id: "106",
          name: "Money In The Bank",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 50,
          qty: "",
          total: "",
        },
        {
          id: "107",
          name: "King of Hitler",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 50,
          qty: "",
          total: "",
        },
        {
          id: "108",
          name: "Top Gun",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 200,
          qty: "",
          total: "",
        },
        {
          id: "109",
          name: "Colour Smoke",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 160,
          qty: "",
          total: "",
        },
        {
          id: "110",
          name: "Selfie Stike - 3 Pcs",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 160,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-18",
      category: "REPEATING SHOTS RIDERS",
      description: "description",
      items: [
        {
          id: "111",
          name: "12 Short - Rider",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 120,
          qty: "",
          total: "",
        },
        {
          id: "112",
          name: "25 Short - Rider",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 240,
          qty: "",
          total: "",
        },
        {
          id: "113",
          name: "30 Short - Rider",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 350,
          qty: "",
          total: "",
        },
        {
          id: "114",
          name: "50 Short - Rider",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 450,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-19",
      category: "REPEATING SHOTS",
      description: "description",
      items: [
        {
          id: "115",
          name: "30 Shorts",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 400,
          qty: "",
          total: "",
        },
        {
          id: "116",
          name: "60 Shorts",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 800,
          qty: "",
          total: "",
        },
        {
          id: "117",
          name: "120 Shorts",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 1600,
          qty: "",
          total: "",
        },
        {
          id: "118",
          name: "240 Shorts",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 3050,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-20",
      category: "AERIAL PIPERS",
      description: "description",
      items: [
        {
          id: "119",
          name: "Chotta Fancy - 4 Varties",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 80,
          qty: "",
          total: "",
        },
        {
          id: "120",
          name: "2' 1/2 Inch Aerial - 5 Variets",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 150,
          qty: "",
          total: "",
        },
        {
          id: "121",
          name: "2' Pipe- 3 PCs ",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 350,
          qty: "",
          total: "",
        },
        {
          id: "122",
          name: "3' 1/2 Pipe ",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 250,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-21",
      category: "CHILDERNS SPECIALS",
      description: "description",
      items: [
        {
          id: "123",
          name: "Ring Gun Small",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 60,
          qty: "",
          total: "",
        },
        {
          id: "124",
          name: "Ring Caps",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 10,
          qty: "",
          total: "",
        },
        {
          id: "125",
          name: "Roll Caps",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 80,
          qty: "",
          total: "",
        },
        {
          id: "126",
          name: "Electric Stone",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 20,
          qty: "",
          total: "",
        },
        {
          id: "127",
          name: " Tip Top",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 30,
          qty: "",
          total: "",
        },
        {
          id: "128",
          name: "Kit Kat",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 40,
          qty: "",
          total: "",
        },
        {
          id: "129",
          name: "Stike",
          img: "img/logo.png",
          unit: "1 PCE",
          actual_amount: "",
          amount: 10,
          qty: "",
          total: "",
        },
      ],
    },
    {
      id: "cat-22",
      category: "GIFT BOX",
      description: "description",
      items: [
        {
          id: "130",
          name: "21 ITEMS - Dora",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 400,
          qty: "",
          total: "",
        },
        {
          id: "131",
          name: "25 ITEMS - Appu",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 600,
          qty: "",
          total: "",
        },
        {
          id: "132",
          name: "30 ITEMS - Superb",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 800,
          qty: "",
          total: "",
        },
        {
          id: "133",
          name: "35 ITEMS - Thunder",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 1000,
          qty: "",
          total: "",
        },
        {
          id: "134",
          name: "41 ITEMS - Rainbow",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 1200,
          qty: "",
          total: "",
        },
        {
          id: "135",
          name: "50 ITEMs - Platina",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 1800,
          qty: "",
          total: "",
        },
        {
          id: "136",
          name: "70 ITEMs - King",
          img: "img/logo.png",
          unit: "1 BOX",
          actual_amount: "",
          amount: 2500,
          qty: "",
          total: "",
        },
      ],
    },
  ],
};

export const itemSlice = createSlice({
  name: "items",
  initialState,
  reducers: {
    addItem: (state, { payload }) => {
      state.items = payload;
    },
    clearItem: (state) => {
      state.items = initialState.items;
    },

    extraReducers: {
      [HYDRATE]: (state) => {
        return {
          ...state,
          ...payload.items,
        };
      },
    },
  },
});

export const { addItem, clearItem } = itemSlice.actions;
export default itemSlice.reducer;
